const FANTAEQUIPOS = [
  {
    fantaEquipo: "AY DE MI",
    presidente: "Federico Smurra",
    email: "x@gmail.com",
    presupuesto: 26100,
    remanente: 16700,
    campeonatos: 4,
    copas: 3,
    campeon_actual: false,
  },
  {
    fantaEquipo: "BALDOSERA",
    presidente: "Maximiliano Ferraris",
    email: "x@gmail.com",
    presupuesto: 25300,
    remanente: 21200,
    campeonatos: 2,
    copas: 0,
    campeon_actual: false,
  },
  {
    fantaEquipo: "DECO",
    presidente: "Sebastian Canosa",
    email: "x@gmail.com",
    presupuesto: 25400,
    remanente: 19900,
    campeonatos: 4,
    copas: 0,
    campeon_actual: false,
  },
  {
    fantaEquipo: "DEP. ARECO",
    presidente: "Santiago Varela",
    email: "x@gmail.com",
    presupuesto: 26200,
    remanente: 22700,
    campeonatos: 1,
    copas: 2, // Sumar 1 copa
    campeon_actual: false,
  },
  {
    fantaEquipo: "EL MARPLATENSE",
    presidente: "Ezequiel Zema",
    email: "x@gmail.com",
    presupuesto: 26200,
    remanente: 17500,
    campeonatos: 6,
    copas: 5,
    campeon_actual: false,
  },
  {
    fantaEquipo: "FIRMAMO",
    presidente: "Maximiliano Gurnik",
    email: "x@gmail.com",
    presupuesto: 25600,
    remanente: 18700,
    campeonatos: 1,
    copas: 2,
    campeon_actual: false,
  },
  {
    fantaEquipo: "FLA 3",
    presidente: "Flavio Smurra",
    email: "x@gmail.com",
    presupuesto: 26000,
    remanente: 15900,
    campeonatos: 2,
    copas: 0,
    campeon_actual: false,
  },
  {
    fantaEquipo: "FLATULENTOS",
    presidente: "Sebastian Mondillo",
    email: "x@gmail.com",
    presupuesto: 26400,
    remanente: 17900,
    campeonatos: 5,
    copas: 1,
    campeon_actual: false,
  },
  {
    fantaEquipo: "INDEPTE. SPURS",
    presidente: "Sergio Castro",
    email: "x@gmail.com",
    presupuesto: 25500,
    remanente: 18900,
    campeonatos: 1,
    copas: 2,
    campeon_actual: false,
  },
  {
    fantaEquipo: "JRFC",
    presidente: "Leonardo Usar",
    email: "x@gmail.com",
    presupuesto: 23800,
    remanente: 23800,
    campeonatos: 0,
    copas: 0,
    campeon_actual: false,
  },
  {
    fantaEquipo: "MORGANTI FC",
    presidente: "Mariano Morganti",
    email: "mmorganti@gmail.com",
    presupuesto: 25800,
    remanente: 13600,
    campeonatos: 2,
    copas: 2,
    campeon_actual: false,
  },
  {
    fantaEquipo: "PDC",
    presidente: "David Alarcón",
    email: "x@gmail.com",
    presupuesto: 28000,
    remanente: 18300,
    campeonatos: 1, // Sumar 1 campeonato
    copas: 1,
    campeon_actual: true, // Asegurar que sea el único campeón actual
  },
  {
    fantaEquipo: "PELOTA DE TRAPO",
    presidente: "Pedro Bombur",
    email: "x@gmail.com",
    presupuesto: 25600,
    remanente: 17600,
    campeonatos: 2,
    copas: 2,
    campeon_actual: false,
  },
  {
    fantaEquipo: "PITUFOS",
    presidente: "Matias Zema",
    email: "x@gmail.com",
    presupuesto: 25100,
    remanente: 23600,
    campeonatos: 2,
    copas: 5,
    campeon_actual: false,
  },
  {
    fantaEquipo: "ROSTOCK",
    presidente: "Leonel chiappetta",
    email: "x@gmail.com",
    presupuesto: 26300,
    remanente: 17600,
    campeonatos: 1,
    copas: 0,
    campeon_actual: false,
  },
  {
    fantaEquipo: "VILLA LURO",
    presidente: "Germán Gomez",
    email: "x@gmail.com",
    presupuesto: 25700,
    remanente: 15900,
    campeonatos: 2,
    copas: 5,
    campeon_actual: false,
  },
];

module.exports = {
  FANTAEQUIPOS
}