const FANTATEAMS = [
  {
    name: "AY DE MI",
    president: "Federico Smurra",
    email: "x@gmail.com",
    budget: 26100,
    remaining: 18000,
  },
  {
    name: "BALDOSERA",
    president: "Maximiliano Ferraris",
    email: "x@gmail.com",
    budget: 25100,
    remaining: 24400,
  },
  {
    name: "DECO",
    president: "Sebastian Canosa",
    email: "x@gmail.com",
    budget: 26300,
    remaining: 19900,
  },
  {
    name: "DEP. ARECO",
    president: "Santiago Varela",
    email: "x@gmail.com",
    budget: 25600,
    remaining: 19100,
  },
  {
    name: "EL MARPLATENSE",
    president: "Ezequiel Zema",
    email: "x@gmail.com",
    budget: 25700,
    remaining: 19500,
  },
  {
    name: "FIRMAMO",
    president: "Maximiliano Gurnik",
    email: "x@gmail.com",
    budget: 25200,
    remaining: 22300,
  },
  {
    name: "FLA 3",
    president: "Flavio Smurra",
    email: "x@gmail.com",
    budget: 25400,
    remaining: 19500,
  },
  {
    name: "FLATULENTOS",
    president: "Sebastian Mondillo",
    email: "x@gmail.com",
    budget: 25500,
    remaining: 17200,
  },
  {
    name: "INDEPTE. SPURS",
    president: "Sergio Castro",
    email: "x@gmail.com",
    budget: 25800,
    remaining: 18400,
  },
  {
    name: "JRFC",
    president: "Leonardo Usar",
    email: "x@gmail.com",
    budget: 26000,
    remaining: 20800,
  },
  {
    name: "MORGANTI FC",
    president: "Mariano Morganti",
    email: "mmorganti@gmail.com",
    budget: 25900,
    remaining: 15900,
  },
  {
    name: "PDC",
    president: "David Alarcón",
    email: "x@gmail.com",
    budget: 26400,
    remaining: 18700,
  },
  {
    name: "PELOTA DE TRAPO",
    president: "Pedro Bombur",
    email: "x@gmail.com",
    budget: 28000,
    remaining: 17300,
  },
  {
    name: "PITUFOS",
    president: "Matias Zema",
    email: "x@gmail.com",
    budget: 25300,
    remaining: 16000,
  },
  {
    name: "ROSTOCK",
    president: "Leonel chiappetta",
    email: "x@gmail.com",
    budget: 25000,
    remaining: 23700,
  },
  {
    name: "VILLA LURO",
    president: "Germán Gomez",
    email: "x@gmail.com",
    budget: 26200,
    remaining: 19500,
  },
];

const LEAGUETEAMS = [
  { team: "Argentinos", state: false },
  { team: "Atl. Tucumán", state: false },
  { team: "Banfield", state: false },
  { team: "Barracas Central", state: false },
  { team: "Belgrano", state: false },
  { team: "Boca", state: false },
  { team: "Central Cordoba", state: false },
  { team: "Defensa y Justicia", state: false },
  { team: "Estudiantes", state: false },
  { team: "Gimnasia", state: false },
  { team: "Godoy Cruz", state: false },
  { team: "Huracán", state: false },
  { team: "Independiente", state: false },
  { team: "Indepte. Rivadavia", state: false },
  { team: "Instituto", state: false },
  { team: "Lanús", state: false },
  { team: "Newell's", state: false },
  { team: "Platense", state: false },
  { team: "Racing", state: false },
  { team: "Riestra", state: false },
  { team: "River", state: false },
  { team: "Rosario Central", state: false },
  { team: "San Lorenzo", state: false },
  { team: "Sarmiento", state: false },
  { team: "Talleres", state: false },
  { team: "Tigre", state: false },
  { team: "Unión", state: false },
  { team: "Vélez", state: false },
];


const POSITIONS = [
  { position: "ARQ", state: false },
  { position: "DEF", state: false },
  { position: "VOL", state: false },
  { position: "DEL", state: false },
];

const PLAYERS = [
  {
    team: "Argentinos",
    player: "Di Cesare, Marco",
    basePrice: 400,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 1100,
  },
  {
    team: "Argentinos",
    player: "Palacios, Tobias",
    basePrice: 100,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Argentinos",
    player: "Vega, Roman",
    basePrice: 200,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 200,
  },
  {
    team: "Argentinos",
    player: "Gondou, Luciano",
    basePrice: 800,
    position: "DEL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 2200,
  },
  {
    team: "Argentinos",
    player: "Romero, Maximiliano",
    basePrice: 300,
    position: "DEL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 1200,
  },
  {
    team: "Argentinos",
    player: "Lescano, Alan",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 1100,
  },
  {
    team: "Argentinos",
    player: "Rodriguez, Alan",
    basePrice: 500,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 2100,
  },
  {
    team: "Banfield",
    player: "Quiros, Aaron",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Boca",
    player: "Brey, Leandro",
    basePrice: 100,
    position: "ARQ",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 100,
  },
  {
    team: "Boca",
    player: "Garcia, Javier",
    basePrice: 300,
    position: "ARQ",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 300,
  },
  {
    team: "Boca",
    player: "Romero, Sergio",
    basePrice: 500,
    position: "ARQ",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 800,
  },
  {
    team: "Boca",
    player: "Figal, Nicolas",
    basePrice: 500,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 1300,
  },
  {
    team: "Boca",
    player: "Valentini, Nicolas",
    basePrice: 400,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Boca",
    player: "Taborda, Vicente",
    basePrice: 400,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 1000,
  },
  {
    team: "Central Cordoba",
    player: "Mansilla, Matias",
    basePrice: 300,
    position: "ARQ",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Central Cordoba",
    player: "Sanabria, Mateo",
    basePrice: 300,
    position: "DEL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 300,
  },
  {
    team: "Central Cordoba",
    player: "Nuss, Thiago",
    basePrice: 300,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Central Cordoba",
    player: "Montoya, Walter",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Defensa y Justicia",
    player: "Barbona, David",
    basePrice: 600,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 2300,
  },
  {
    team: "Defensa y Justicia",
    player: "Romero, Franco",
    basePrice: 200,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 200,
  },
  {
    team: "Defensa y Justicia",
    player: "Sosa Vivaldi, Elian",
    basePrice: 100,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 100,
  },
  {
    team: "Estudiantes",
    player: "Fernandez, Nicolas",
    basePrice: 100,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 100,
  },
  {
    team: "Estudiantes",
    player: "Mancuso, Eros",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 1200,
  },
  {
    team: "Estudiantes",
    player: "Meza, Eric",
    basePrice: 400,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 400,
  },
  {
    team: "Estudiantes",
    player: "Correa, Javier",
    basePrice: 400,
    position: "DEL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 2600,
  },
  {
    team: "Estudiantes",
    player: "Atum, Axel",
    basePrice: 200,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 200,
  },
  {
    team: "Gimnasia",
    player: "Morales, Leonardo",
    basePrice: 400,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 1000,
  },
  {
    team: "Gimnasia",
    player: "Ramirez, Eric",
    basePrice: 400,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 1100,
  },
  {
    team: "Godoy Cruz",
    player: "Arce, Lucas",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 800,
  },
  {
    team: "Godoy Cruz",
    player: "Lopez Muñoz, Hernan",
    basePrice: 600,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 2400,
  },
  {
    team: "Huracán",
    player: "Perez Mosqueira, Marcelo",
    basePrice: 300,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Huracán",
    player: "Alarcon, Williams",
    basePrice: 400,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 1200,
  },
  {
    team: "Independiente",
    player: "Maestro Puch, Ignacio",
    basePrice: 300,
    position: "DEL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 500,
  },
  {
    team: "Independiente",
    player: "Costa, Ayrton",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 800,
  },
  {
    team: "Independiente",
    player: "Parmo, Tomas",
    basePrice: 100,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Indepte. Rivadavia",
    player: "Bianchi, Bruno",
    basePrice: 400,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Instituto",
    player: "Rodriguez, Gregorio",
    basePrice: 200,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Instituto",
    player: "Bochi, Roberto",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 600,
  },
  {
    team: "Lanús",
    player: "Boggio, Luciano",
    basePrice: 400,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Newell's",
    player: "Mendez, Armando",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 700,
  },
  {
    team: "Newell's",
    player: "Ramirez, Juan Ignacio",
    basePrice: 400,
    position: "DEL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 2000,
  },
  {
    team: "Newell's",
    player: "Aguirre, Brian",
    basePrice: 400,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 600,
  },
  {
    team: "Platense",
    player: "Gomez, Ivan",
    basePrice: 400,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 900,
  },
  {
    team: "Platense",
    player: "Rivero, Braian",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Racing",
    player: "Almendra, Agustin",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 500,
  },
  {
    team: "River",
    player: "Barco, Esequiel",
    basePrice: 800,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 2200,
  },
  {
    team: "Rosario Central",
    player: "Gimenez, Juan",
    basePrice: 100,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 100,
  },
  {
    team: "Rosario Central",
    player: "Modica, Agustin",
    basePrice: 100,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 100,
  },
  {
    team: "Rosario Central",
    player: "Campaz, Jaminton",
    basePrice: 800,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 1700,
  },
  {
    team: "San Lorenzo",
    player: "Hernandez, Nicolas",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 300,
  },
  {
    team: "San Lorenzo",
    player: "Romaña, Jhohan",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 900,
  },
  {
    team: "San Lorenzo",
    player: "Goyeneche, Juan Ignacio",
    basePrice: 100,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 100,
  },
  {
    team: "San Lorenzo",
    player: "Blanco, Sebastian",
    basePrice: 500,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 600,
  },
  {
    team: "Sarmiento",
    player: "Monetti, Fernando",
    basePrice: 300,
    position: "ARQ",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Sarmiento",
    player: "Pourtau, Jeronimo",
    basePrice: 100,
    position: "ARQ",
    fantaTeam: "PITUFOS",
    boughtPrice: 100,
  },
  {
    team: "Sarmiento",
    player: "Morales Bravo, Ivan",
    basePrice: 200,
    position: "DEL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 200,
  },
  {
    team: "Talleres",
    player: "Zalazar, David",
    basePrice: 200,
    position: "VOL",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 200,
  },
  {
    team: "Tigre",
    player: "Garay, Martin",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Tigre",
    player: "Armoa, Blas",
    basePrice: 400,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 900,
  },
  {
    team: "Tigre",
    player: "Londoño, Flabian",
    basePrice: 300,
    position: "DEL",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Unión",
    player: "Corvalan, Claudio",
    basePrice: 400,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Unión",
    player: "Fascendini, Valentin",
    basePrice: 100,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 100,
  },
  {
    team: "Unión",
    player: "Pitton, Bruno",
    basePrice: 300,
    position: "DEF",
    fantaTeam: "PITUFOS",
    boughtPrice: 300,
  },
  {
    team: "Unión",
    player: "Mosqueira, Joaquin",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 500,
  },
  {
    team: "Unión",
    player: "Roldan, Enzo",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 700,
  },
  {
    team: "Unión",
    player: "Verde, Lionel",
    basePrice: 100,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 100,
  },
  {
    team: "Vélez",
    player: "Marchiori, Tomas",
    basePrice: 500,
    position: "ARQ",
    fantaTeam: "PITUFOS",
    boughtPrice: 1000,
  },
  {
    team: "Vélez",
    player: "Gomez, Elias",
    basePrice: 400,
    position: "DEF",
    fantaTeam: "MORGANTI FC",
    boughtPrice: 1000,
  },
  {
    team: "Vélez",
    player: "Fernandez, Thiago",
    basePrice: 100,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 100,
  },
  {
    team: "Vélez",
    player: "Florentin, Jose",
    basePrice: 300,
    position: "VOL",
    fantaTeam: "PITUFOS",
    boughtPrice: 700,
  },
];

module.exports = {
  FANTATEAMS,
  LEAGUETEAMS,
  POSITIONS,
  PLAYERS,
};
