const FANTATEAMS = [
  {
    name: "AY DE MI",
    president: "Federico Smurra",
    email: "x@gmail.com",
    budget: 26100,
    remaining: 18000,
  },
  {
    name: "BALDOSERA",
    president: "Maximiliano Ferraris",
    email: "x@gmail.com",
    budget: 25100,
    remaining: 24400,
  },
  {
    name: "DECO",
    president: "Sebastian Canosa",
    email: "x@gmail.com",
    budget: 26300,
    remaining: 19900,
  },
  {
    name: "DEP. ARECO",
    president: "Santiago Varela",
    email: "x@gmail.com",
    budget: 25600,
    remaining: 19100,
  },
  {
    name: "EL MARPLATENSE",
    president: "Ezequiel Zema",
    email: "x@gmail.com",
    budget: 25700,
    remaining: 19500,
  },
  {
    name: "FIRMAMO",
    president: "Maximiliano Gurnik",
    email: "x@gmail.com",
    budget: 25200,
    remaining: 22300,
  },
  {
    name: "FLA 3",
    president: "Flavio Smurra",
    email: "x@gmail.com",
    budget: 25400,
    remaining: 19500,
  },
  {
    name: "FLATULENTOS",
    president: "Sebastian Mondillo",
    email: "x@gmail.com",
    budget: 25500,
    remaining: 17200,
  },
  {
    name: "INDEPTE. SPURS",
    president: "Sergio Castro",
    email: "x@gmail.com",
    budget: 25800,
    remaining: 18400,
  },
  {
    name: "JRFC",
    president: "Leonardo Usar",
    email: "x@gmail.com",
    budget: 26000,
    remaining: 20800,
  },
  {
    name: "MORGANTI FC",
    president: "Mariano Morganti",
    email: "mmorganti@gmail.com",
    budget: 25900,
    remaining: 15900,
  },
  {
    name: "PDC",
    president: "David Alarcón",
    email: "x@gmail.com",
    budget: 26400,
    remaining: 18700,
  },
  {
    name: "PELOTA DE TRAPO",
    president: "Pedro Bombur",
    email: "x@gmail.com",
    budget: 28000,
    remaining: 17300,
  },
  {
    name: "PITUFOS",
    president: "Matias Zema",
    email: "x@gmail.com",
    budget: 25300,
    remaining: 16000,
  },
  {
    name: "ROSTOCK",
    president: "Leonel chiappetta",
    email: "x@gmail.com",
    budget: 25000,
    remaining: 23700,
  },
  {
    name: "VILLA LURO",
    president: "Germán Gomez",
    email: "x@gmail.com",
    budget: 26200,
    remaining: 19500,
  },
];

const LEAGUETEAMS = [
  { team: "Argentinos", state: false },
  { team: "Atl. Tucumán", state: false },
  { team: "Banfield", state: false },
  { team: "Barracas Central", state: false },
  { team: "Belgrano", state: false },
  { team: "Boca", state: false },
  { team: "Central Cordoba", state: false },
  { team: "Defensa y Justicia", state: false },
  { team: "Estudiantes", state: false },
  { team: "Gimnasia", state: false },
  { team: "Godoy Cruz", state: false },
  { team: "Huracán", state: false },
  { team: "Independiente", state: false },
  { team: "Indepte. Rivadavia", state: false },
  { team: "Instituto", state: false },
  { team: "Lanús", state: false },
  { team: "Newell's", state: false },
  { team: "Platense", state: false },
  { team: "Racing", state: false },
  { team: "Riestra", state: false },
  { team: "River", state: false },
  { team: "Rosario Central", state: false },
  { team: "San Lorenzo", state: false },
  { team: "Sarmiento", state: false },
  { team: "Talleres", state: false },
  { team: "Tigre", state: false },
  { team: "Unión", state: false },
  { team: "Vélez", state: false },
];

module.exports = {
  FANTATEAMS,
  LEAGUETEAMS,
};


const POSITIONS = [
  { position: "Arqueros", state: false },
  { position: "Defensores", state: false },
  { position: "Mediocampistas", state: false },
  { position: "Delanteros", state: false },
];

module.exports = {
  FANTATEAMS,
  LEAGUETEAMS,
  POSITIONS,
};
